// generated by stringer -type=PaaType; DO NOT EDIT

package paa

import "fmt"

const (
	_PaaType_name_0 = "RGBA4444"
	_PaaType_name_1 = "RGBA5551"
	_PaaType_name_2 = "GrayWithAlpha"
	_PaaType_name_3 = "RGBA8888"
	_PaaType_name_4 = "DXT1DXT2DXT3DXT4DXT5"
)

var (
	_PaaType_index_0 = [...]uint8{8}
	_PaaType_index_1 = [...]uint8{8}
	_PaaType_index_2 = [...]uint8{13}
	_PaaType_index_3 = [...]uint8{8}
	_PaaType_index_4 = [...]uint8{4, 8, 12, 16, 20}
)

func (i PaaType) String() string {
	switch {
	case i == 17476:
		return _PaaType_name_0
	case i == 21841:
		return _PaaType_name_1
	case i == 32896:
		return _PaaType_name_2
	case i == 34952:
		return _PaaType_name_3
	case 65281 <= i && i <= 65285:
		i -= 65281
		lo := uint8(0)
		if i > 0 {
			lo = _PaaType_index_4[i-1]
		}
		return _PaaType_name_4[lo:_PaaType_index_4[i]]
	default:
		return fmt.Sprintf("PaaType(%d)", i)
	}
}
